version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flask-mysql
    environment:
      MYSQL_ROOT_PASSWORD: LoginAppDbPwd@2025
      MYSQL_DATABASE: loginapp
      MYSQL_USER: loginappuser
      MYSQL_PASSWORD: LoginAppDbPwd@2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=loginappuser
      - MYSQL_PASSWORD=LoginAppDbPwd@2025
      - MYSQL_DB=loginapp
      - MYSQL_PORT=3306
    depends_on:
      - mysql

volumes:
  mysql_data:
